#! /bin/sh

########################################
## Shell script created by xiaoqiang
## @brief
## @date
########################################

../Nicon/package/ZXPSignCmd -sign ../IconTemplate IconTemplate.1.0.0.zxp ../Nicon/package/nicon.p12 04041029 -tsa https://timestamp.geotrust.com/tsa
